version: '3.4'

services:
  aurorasms:
    image: ${DOCKER_REGISTRY-}aurorasms
    build:
      context: .
      dockerfile: AuroraSMS/Dockerfile
    environment:
      dbhost: db
      dbdb: AuroraSMS
      dbuser: root
      dbpass: example
      apikey: none 
    depends_on:
      db:
         condition: service_healthy
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
